// SPDX-License-Identifier: MIT
// Generated by scripts/extract-api.ts from the package's declarations — do not edit.
import data from '~/content/api/CARRIED_OVER_TAG.json';
import { SymbolPage } from '~/shell/doc';

export default function CarriedOverTagPage(): React.ReactElement {
  return <SymbolPage data={data} ns="pages/reference/carried-over-tag" />;
}
