// SPDX-License-Identifier: MIT
// Generated by scripts/extract-api.ts from the package's declarations — do not edit.
import data from '~/content/api/createNavigator.json';
import { SymbolPage } from '~/shell/doc';

export default function CreateNavigatorPage(): React.ReactElement {
  return <SymbolPage data={data} ns="pages/reference/create-navigator" />;
}
