// SPDX-License-Identifier: MIT
// Generated by scripts/extract-api.ts from the package's declarations — do not edit.
import data from '~/content/api/DefaultItemDetail.json';
import { SymbolPage } from '~/shell/doc';

export default function DefaultItemDetailPage(): React.ReactElement {
  return <SymbolPage data={data} ns="pages/reference/default-item-detail" />;
}
