// SPDX-License-Identifier: MIT
// Generated by scripts/extract-api.ts from the package's declarations — do not edit.
import data from '~/content/api/PinnedStrip.json';
import { SymbolPage } from '~/shell/doc';

export default function PinnedStripPage(): React.ReactElement {
  return <SymbolPage data={data} ns="pages/reference/pinned-strip" />;
}
