// SPDX-License-Identifier: MIT
// Generated by scripts/extract-api.ts from the package's declarations — do not edit.
import data from '~/content/api/ScrollTopButton.json';
import { SymbolPage } from '~/shell/doc';

export default function ScrollTopButtonPage(): React.ReactElement {
  return <SymbolPage data={data} ns="pages/reference/scroll-top-button" />;
}
