// SPDX-License-Identifier: MIT
// Generated by scripts/extract-api.ts from the package's declarations — do not edit.
import schedulerFormatters_ from '~/content/api/SchedulerFormatters.json';
import deepPartial_ from '~/content/api/DeepPartial.json';
import pluralForms_ from '~/content/api/PluralForms.json';
import schedulerLocalization_ from '~/content/api/SchedulerLocalization.json';
import { TypeGroupPage } from '~/shell/doc';

const TYPES = [schedulerFormatters_, deepPartial_, pluralForms_, schedulerLocalization_];

export default function TypesLocalizationPage(): React.ReactElement {
  return <TypeGroupPage types={TYPES} ns="pages/reference/types-localization" />;
}
