// SPDX-License-Identifier: MIT
// Generated by scripts/extract-api.ts from the package's declarations — do not edit.
import middleware_ from '~/content/api/Middleware.json';
import navState_ from '~/content/api/NavState.json';
import activationSource_ from '~/content/api/ActivationSource.json';
import closeReason_ from '~/content/api/CloseReason.json';
import headerReason_ from '~/content/api/HeaderReason.json';
import navPosition_ from '~/content/api/NavPosition.json';
import schedulerHandlers_ from '~/content/api/SchedulerHandlers.json';
import schedulerEvents_ from '~/content/api/SchedulerEvents.json';
import { TypeGroupPage } from '~/shell/doc';

const TYPES = [
  middleware_,
  navState_,
  activationSource_,
  closeReason_,
  headerReason_,
  navPosition_,
  schedulerHandlers_,
  schedulerEvents_,
];

export default function TypesEventsPage(): React.ReactElement {
  return <TypeGroupPage types={TYPES} ns="pages/reference/types-events" />;
}
