// SPDX-License-Identifier: MIT
// Generated by scripts/extract-api.ts from the package's declarations — do not edit.
import tokenName_ from '~/content/api/TokenName.json';
import baseSlotProps_ from '~/content/api/BaseSlotProps.json';
import cardContentContext_ from '~/content/api/CardContentContext.json';
import elementProps_ from '~/content/api/ElementProps.json';
import emptyContext_ from '~/content/api/EmptyContext.json';
import headerContext_ from '~/content/api/HeaderContext.json';
import itemDetailContext_ from '~/content/api/ItemDetailContext.json';
import itemProps_ from '~/content/api/ItemProps.json';
import navLabelContext_ from '~/content/api/NavLabelContext.json';
import overflowCellContext_ from '~/content/api/OverflowCellContext.json';
import overflowColumn_ from '~/content/api/OverflowColumn.json';
import ownerState_ from '~/content/api/OwnerState.json';
import partExtraProps_ from '~/content/api/PartExtraProps.json';
import pinSentinelProps_ from '~/content/api/PinSentinelProps.json';
import renderItemContext_ from '~/content/api/RenderItemContext.json';
import schedulerPart_ from '~/content/api/SchedulerPart.json';
import schedulerSlotProps_ from '~/content/api/SchedulerSlotProps.json';
import schedulerSlots_ from '~/content/api/SchedulerSlots.json';
import slotProps_ from '~/content/api/SlotProps.json';
import { TypeGroupPage } from '~/shell/doc';

const TYPES = [
  tokenName_,
  baseSlotProps_,
  cardContentContext_,
  elementProps_,
  emptyContext_,
  headerContext_,
  itemDetailContext_,
  itemProps_,
  navLabelContext_,
  overflowCellContext_,
  overflowColumn_,
  ownerState_,
  partExtraProps_,
  pinSentinelProps_,
  renderItemContext_,
  schedulerPart_,
  schedulerSlotProps_,
  schedulerSlots_,
  slotProps_,
];

export default function TypesSlotsPage(): React.ReactElement {
  return <TypeGroupPage types={TYPES} ns="pages/reference/types-slots" />;
}
