// SPDX-License-Identifier: MIT
// Generated by scripts/extract-api.ts from the package's declarations — do not edit.
import cardVariant_ from '~/content/api/CardVariant.json';
import classicLevelKey_ from '~/content/api/ClassicLevelKey.json';
import classicTagKey_ from '~/content/api/ClassicTagKey.json';
import colorScheme_ from '~/content/api/ColorScheme.json';
import dateInput_ from '~/content/api/DateInput.json';
import density_ from '~/content/api/Density.json';
import itemOf_ from '~/content/api/ItemOf.json';
import landingTarget_ from '~/content/api/LandingTarget.json';
import levelDefinition_ from '~/content/api/LevelDefinition.json';
import overflowGroup_ from '~/content/api/OverflowGroup.json';
import placedCard_ from '~/content/api/PlacedCard.json';
import presetName_ from '~/content/api/PresetName.json';
import schedulerItem_ from '~/content/api/SchedulerItem.json';
import segmentInput_ from '~/content/api/SegmentInput.json';
import shiftPatternEntry_ from '~/content/api/ShiftPatternEntry.json';
import shiftRole_ from '~/content/api/ShiftRole.json';
import shiftSegment_ from '~/content/api/ShiftSegment.json';
import shiftWindow_ from '~/content/api/ShiftWindow.json';
import sortDirection_ from '~/content/api/SortDirection.json';
import tagDefinition_ from '~/content/api/TagDefinition.json';
import timelineLayout_ from '~/content/api/TimelineLayout.json';
import viewKind_ from '~/content/api/ViewKind.json';
import wallClock_ from '~/content/api/WallClock.json';
import overflowSort_ from '~/content/api/OverflowSort.json';
import schedulerHandle_ from '~/content/api/SchedulerHandle.json';
import schedulerState_ from '~/content/api/SchedulerState.json';
import resolvedLevel_ from '~/content/api/ResolvedLevel.json';
import sortableColumn_ from '~/content/api/SortableColumn.json';
import schedulerController_ from '~/content/api/SchedulerController.json';
import schedulerModel_ from '~/content/api/SchedulerModel.json';
import schedulerStoreState_ from '~/content/api/SchedulerStoreState.json';
import schedulerViewModel_ from '~/content/api/SchedulerViewModel.json';
import scrollFacts_ from '~/content/api/ScrollFacts.json';
import navigator_ from '~/content/api/Navigator.json';
import navigatorHooks_ from '~/content/api/NavigatorHooks.json';
import reducedMotion_ from '~/content/api/ReducedMotion.json';
import pinEngine_ from '~/content/api/PinEngine.json';
import { TypeGroupPage } from '~/shell/doc';

const TYPES = [
  cardVariant_,
  classicLevelKey_,
  classicTagKey_,
  colorScheme_,
  dateInput_,
  density_,
  itemOf_,
  landingTarget_,
  levelDefinition_,
  overflowGroup_,
  placedCard_,
  presetName_,
  schedulerItem_,
  segmentInput_,
  shiftPatternEntry_,
  shiftRole_,
  shiftSegment_,
  shiftWindow_,
  sortDirection_,
  tagDefinition_,
  timelineLayout_,
  viewKind_,
  wallClock_,
  overflowSort_,
  schedulerHandle_,
  schedulerState_,
  resolvedLevel_,
  sortableColumn_,
  schedulerController_,
  schedulerModel_,
  schedulerStoreState_,
  schedulerViewModel_,
  scrollFacts_,
  navigator_,
  navigatorHooks_,
  reducedMotion_,
  pinEngine_,
];

export default function TypesModelPage(): React.ReactElement {
  return <TypeGroupPage types={TYPES} ns="pages/reference/types-model" />;
}
