// SPDX-License-Identifier: MIT
// Generated by scripts/extract-api.ts from the package's declarations — do not edit.
import listOptions_ from '~/content/api/ListOptions.json';
import pinningOptions_ from '~/content/api/PinningOptions.json';
import timelineOptions_ from '~/content/api/TimelineOptions.json';
import shiftOptions_ from '~/content/api/ShiftOptions.json';
import listViewProps_ from '~/content/api/ListViewProps.json';
import schedulerProps_ from '~/content/api/SchedulerProps.json';
import timelineViewProps_ from '~/content/api/TimelineViewProps.json';
import formatterOptions_ from '~/content/api/FormatterOptions.json';
import timelineLayoutOptions_ from '~/content/api/TimelineLayoutOptions.json';
import resolvedFlags_ from '~/content/api/ResolvedFlags.json';
import schedulerFlags_ from '~/content/api/SchedulerFlags.json';
import schedulerOptions_ from '~/content/api/SchedulerOptions.json';
import navigatorOptions_ from '~/content/api/NavigatorOptions.json';
import pinEngineOptions_ from '~/content/api/PinEngineOptions.json';
import { TypeGroupPage } from '~/shell/doc';

const TYPES = [
  listOptions_,
  pinningOptions_,
  timelineOptions_,
  shiftOptions_,
  listViewProps_,
  schedulerProps_,
  timelineViewProps_,
  formatterOptions_,
  timelineLayoutOptions_,
  resolvedFlags_,
  schedulerFlags_,
  schedulerOptions_,
  navigatorOptions_,
  pinEngineOptions_,
];

export default function TypesOptionsPage(): React.ReactElement {
  return <TypeGroupPage types={TYPES} ns="pages/reference/types-options" />;
}
