// SPDX-License-Identifier: MIT
// Generated by scripts/extract-api.ts from the package's declarations — do not edit.
import data from '~/content/api/useScheduler.json';
import { SymbolPage } from '~/shell/doc';

export default function UseSchedulerPage(): React.ReactElement {
  return <SymbolPage data={data} ns="pages/reference/use-scheduler" />;
}
